
ALTER TYPE gatewayStatus
	ADD VALUE 'ERROR_NO_USB_DEVICE'; 
ALTER TYPE gatewayStatus
	ADD VALUE 'ERROR_FIFO_FILE'; 

ALTER TYPE sensorStatus
	ADD VALUE 'UNSTABLE_VOLTAGE'; 
ALTER TYPE sensorStatus
	ADD VALUE 'UNSTABLE_RSSI'; 
