package com.orange.flexoffice.dao.common.model.enumeration;

/**
 * E_ConfigurationKey
 * @author oab
 *
 */
public enum E_ConfigurationKey {
	LAST_CONNECTION_DURATION,
	OCCUPANCY_TIMEOUT,
	BOOKING_DURATION,
	LAST_RESERVED_COUNT,
	DATE_BEGIN_DAY,
	DATE_END_DAY,
	TEACHIN_TIMEOUT,
	KEEP_STAT_DATA_IN_DAYS,
	THRESHOLD_ENABLED_ADVANCEDRESEARCH_OF_ROOMS,
	AGENT_STATUS_TIMEOUT,
	DASHBOARD_STATUS_TIMEOUT,
	MEETINGROOM_STATUS_TIMEOUT,
	WS_REFRESH_INTERVAL,
	INACTIVITY_TIME,
	HOUR_START,
	HOUR_END,
	ORGANIZER_MANDATORY,
	SUBJECT_MANDATORY,
	ACK_TIME,
	USER_CAN_CANCEL,
	CAN_SHOW_SUBJECT,
	CAN_SHOW_ORGANIZER,
	DURATION_STEP,
	PAGES_SHIFT_INTERVAL,
	NB_ROOMS_PER_PAGE,
	VIRTUAL_KEYBOARD,
	KEYBOARD_LANG,
	DASHBOARD_START_DATE,
	DASHBOARD_MAX_BOOKINGS,
	SYNCHRO_TIME;
}
