package com.orange.flexoffice.business.enums;

public enum Status {
	
	// FOR PA
	DISCONNECTED,
	CONNECTING,
	CONNECTED,
	
	// FOR INCOMING CALLS
	RINGING,
        ONGOING,
        
	// FOR DOWNLOAD VIDEO
	WAITING_FOR_VALIDATION,
	IN_PROGRESS,
	COMPLETE,
	STOPEED,
	
	// FOR AUTHENTICATION PROCESS
	ATS_WORKSTATION_CONNECTED,
	ATS_WORKSTATION_DISCONNECTED,
	ATS_SERVER_OFF,
	ATS_SERVER_ON;
	
}
